### ISSUE TITLE
Holz Verkauf

### ISSUE THREAD

**Issue by Sylter** [vabene1111/RL-4.0#107]
beim Normalen Händler wo Äpfel und so zu verkaufen sind geht es nicht zu verkaufen, gibt auch keine andere Verkaufsmöglichkeit

**Comment by Sylter** [comment]
also Faulbaum bekommt man und kann es nirgends verkaufen

**Comment by vabene1111** [comment]
holz wird zu kohle beim kohle verarbeiter und kann dann an jedem markt verkauft werden
