### ISSUE TITLE
Jagtgebiet

### ISSUE THREAD

**Issue by Eggers1** [vabene1111/RL-4.0#111]
Lager 1 (322042)

das auto spawnt komisch es steht halb in der luft.
der markt ist unter dem haus wo es eigentlich drin stehen sollte.
eventuell ein atm reinstellen
man kann dort keine jagtwaffen kaufen und auch kein jagt messer was sehr wichtig wäre
ich würde das lager versetzen sieht komisch aus wenn es so halb am berg steht.
und vielleicht noch ein bisschen verschönern.

Lager 2  

ist soweit okay von der lage her aber die shops und sowas sollten bearbeitet werden. wie bei lager 1. eventuell auch noch mal verschönern.

Lager 3: (337029)

BITTE komplett überarbeiten. steht im walt an einen sehr steilen hang. Geht Garnicht

**Comment by Gurkenschurke** [comment]
Und ganz wichtig : Es gibt nirgends eine Campingausrüstung um Felle , Wolle & Fleisch zu verarbeiten.

**Comment by br1zey** [comment]
im Jagt lager am feuer z.b. kann man fleich verarbeiten
