### ISSUE TITLE
Verbesserung : Polizei (Mehrere im Kommentar)

### ISSUE THREAD

**Issue by pyrox25** [vabene1111/RL-4.0#117]
Die Polizei benötigt Sniper Waffen. Balance zwischen Zivilist und Polizei ist da zu hoch

Die Polizei benötigt eine Oespry um schneller von A nach B zu kommen, evtl Taktisches Eindringen in Gebäuden ueber die Luft möglich

Die Polizei benötigt die Taschenlampe um auf die Karte schauen zu können (Bei Zivilisten im Rebellenmarkt ist dies vorhanden)

Die Polizei benötigt Deutsche Sirenen. Wenn man auf die Taste 2 drückt, dass dann Deutsches Martinshorn kommt

Die Polizei benötigt Zivile Bekleidung (Evtl. 5 aus dem Ziv Shop, so können Undercover Aktionen besser geplant werden. Fördert das RP)

**Comment by vabene1111** [comment]
einige Punkte sehr gute Ideen ...
