### ISSUE TITLE
Neuer Freezepunkt

### ISSUE THREAD

**Issue by Sylter** [vabene1111/RL-4.0#125]
in der Nähe von der Kupferschmiede bei Melbourne habe ich zweimal in Folge ein Freeze mit dem Merlin gehabt
ich war zwischen 200 und 400 m Höhe, 264 Km/h schnell, Fluggerät Merlin
anbei ein Bild mit der ungefähren Stelle
http://www.pic-upload.de/view-28807962/Freezepunkt2.png.html

**Comment by vabene1111** [comment]
habs beim andern rein gemacht
