### ISSUE TITLE
Polizei Shop [Standard-Ausrüstung]

### ISSUE THREAD

**Issue by Eggers1** [vabene1111/RL-4.0#135]
Gekaufter Entfernungsmesser gibt keine Entferung an ?!
Reddot visiere haben keinen rotenpunkt? 
Item [ Fulton MX991 ] ohne erkennbaren Zweck (Herrausnehmen)

Uhr fehlt
Wichtig Funkgerädt fehlt
Karte fehlt

**Comment by HrSh3rl0ck** [comment]
Das Fulton funktioniert in allen Fraktionen! Man muss es wenn man auf der Karte ist mit seinem ACE Menü einschalten!!!! Und es gibt noch keine Funkgeräte weil kein TFR installiert ist!
