### ISSUE TITLE
Alice Springs : Bank

### ISSUE THREAD

**Issue by Gurkenschurke** [vabene1111/RL-4.0#143]
Wenn man in der Bank von hinten an den Geldautomat geht , Bugt man in den Boden. Allerdings kommt man ohne probleme wieder raus.
screen: http://images.akamai.steamusercontent.com/ugc/398927211172742657/816385B7C7F649C0B77F9175D3C40150971CF48E/

**Comment by vabene1111** [comment]
liegt am modell der bank
