### ISSUE TITLE
Pistole : FNX 45 

### ISSUE THREAD

**Issue by Gurkenschurke** [vabene1111/RL-4.0#144]
Es ist nicht möglich mit der Pistole über Kimme & Korn zu zielen. Wenn man es versucht kommt eine nach oben links verschobene sicht die es einem unmöglich macht genaue Schüsse abzugeben.

**Comment by vabene1111** [comment]
ich glaube das ist wegen ace .. muss ich mal testen

**Comment by Gurkenschurke** [comment]
habe festgestellt das das auch bei dem Rebellen Revolver ( Rhino heisst der glaub ich ) so is
