### ISSUE TITLE
Gebrauchtwagen

### ISSUE THREAD

**Issue by Gurkenschurke** [vabene1111/RL-4.0#150]
Limousine - total verbuggt ( anbauteile fliegen kreuz & quer durch die Gegend ) nach einparken in die  Garage scheint aber wieder alles ok zu sein.

Mini & Mini Sport - werden beim Händler fehlerhaft angezeigt ( fehlende Türen , Fenster und Co.) , spawnen nach Kauf aber richtig.

Discovery - Die Farben Schwarz & Silber werden werden beide gleich angezeigt. Nicht zu deffinieren. Könnte schwarz oder Grau sein.

Screens folgen in kürze .... sry. ;)

**Comment by vabene1111** [comment]
fehler der arma engine oder in einem der addons den ich nicht fixen kann
