### ISSUE TITLE
Polizei Hq Mel. Schild vom Waffenverkaufsstand Abgebaut

### ISSUE THREAD

**Issue by Sauerbruch** [vabene1111/RL-4.0#153]
Verkaufstand wegen Biltzer abgebaut

**Comment by StephanLocke** [comment]
Auch Garage und Shop im EG wurden abgebaut mit Blitzer aufstellen und abbauen.

**Comment by vabene1111** [comment]
muss nicht gefixt werden baut einfach keine blitzer ins HQ :D ausserdem konnte ich es nicht reproduzieren
