### ISSUE TITLE
Helikopter Kauf in Melbourne gegenüber vom Krankenhaus

### ISSUE THREAD

**Issue by Sylter** [vabene1111/RL-4.0#155]
Geld wird vom Konto abgebucht jedoch bekommt man keinen Helikopter
http://www.pic-upload.de/view-28826427/2015-11-11_00001.jpg.html

**Comment by br1zey** [comment]
ich konnte ein kaufen der aber leider sonst woo spawnt denke er sollte eigentlich auf dem krankenhaus spawn aber der marker ist zu weit vom Gebäude weg und er findet das nicht habe den marker auf der map neu gesetzt
