### ISSUE TITLE
Kein Angebot in der Cocktailbar!? 

### ISSUE THREAD

**Issue by StephanLocke** [vabene1111/RL-4.0#158]
In Melbourne am Markt in der Coctailbar gibt es kein Angebot, habe Lizensen und kann nichts tun dort. 

?? 

Coordinate 310104

**Comment by PeetPunisher** [comment]
du musst auch erst obst farmen ich hab das schon ge testet es geht die coctails herzustellen und mann kann sie auch verkaufen
