### ISSUE TITLE
Base building

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#160]
Base building funktioniert so weit, nur ist es blöd umgesetzt. heißt das jeder drauf zugriff hat, und dabei sind es leider auch noch fertige Gebäude. zb großer Wachturm der übertrieben ist. würde es rausnehmen und irgendwann ein anderes System reinmachen!!!

**Comment by vabene1111** [comment]
ich lasse es erstmal drin da die lizenz ja eh von admins ausgeben wird , du hast aber recht
