### ISSUE TITLE
Verbesserungen!!!! [Weed]

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#161]
Ich frage mich warum ein neues Weedfeld gebaut wird wenn es schon eins gibt!!!!

Weedfeld: 				333/177
http://grabilla.com/05b0d-2e53abd0-82f2-4dec-bc94-986b893c6393.html#
http://grabilla.com/05b0d-7bdc9db5-1cc0-4771-ae73-6b6ee0d7ffeb.html#

**Comment by br1zey** [comment]
so angenommen
