### ISSUE TITLE
Verbesserungen!!!! [ÖL]

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#162]
Ein Verbesserungsvorschlag für ÖL!!!!

Ölfeld:  				187/157
http://grabilla.com/05b0d-1abff21e-6ccb-4bd6-8ae5-e55ee6434752.html#
http://grabilla.com/05b0d-882ff517-dd2e-48a4-9154-0aad1a3882ba.html#

Ölverarbeitung: 			041/176
http://grabilla.com/05b0d-02b11d6c-b440-4c8d-a414-6e621185f65d.html#

Ölhändler:				128/277
http://grabilla.com/05b0d-bb59a140-5740-414c-b9af-0b5a5b560529.html#
http://grabilla.com/05b0d-7f225f97-5107-46ca-88d6-406c1d2563c9.html#

**Comment by br1zey** [comment]
übernomen
