### ISSUE TITLE
Verbesserungen!!!! [Salz]

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#163]
Ein Verbesserungsvorschlag für Salz!!!!

Salzmine:				        ok

Salzverarbeitung:			231/197
http://grabilla.com/05b0d-96d916f6-242f-4e03-ba5a-1fdb3e3cd6f2.html#
http://grabilla.com/05b0d-30d46f31-e409-409e-836a-7feca1dd3d78.html#

Salzhändler:				309/188
http://grabilla.com/05b0d-bf825246-443b-4a34-a590-bdeb815b6f47.html#
http://grabilla.com/05b0d-23ac1b0b-e4e5-4606-94f4-4eaab363a0f8.html#

**Comment by br1zey** [comment]
OK
