### ISSUE TITLE
Verbesserungen!!!! [Zement]

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#164]
Ein Verbesserungsvorschlag für Zement!!!!

Steinbruch:				ok

Zementverarbeitung:		041/177
http://grabilla.com/05b0d-8bd22604-9ecd-410b-b8fe-d4e8364773dd.html#
http://grabilla.com/05b0d-4cd521a1-bf11-43a4-a150-197636f8359b.html#

Zementhändler			038/149
http://grabilla.com/05b0d-dc72d163-7f7a-4c70-99fc-4ad73ef4246d.html#
http://grabilla.com/05b0d-8b19bd79-af77-4136-aac3-0b929df34d38.html#

**Comment by br1zey** [comment]
Ok
