### ISSUE TITLE
Verbesserungen!!!! [Schwarzmarkt]

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#166]
Die aktuellen Schwarzmärkte sind einfach irgendwo in der wüste und es steht da ein schild verloren rum sieht scheiße aus daher ein Vorschlag, bei 290/366 und den anderen bei 195/239 passt besser zum Schwarzmarkt.
http://grabilla.com/05b0d-d0009665-650e-4b3a-b736-3a8a99e60d22.html#
http://grabilla.com/05b0d-f3ea2a33-81df-4f6a-81a6-fc99b26a9570.html#

**Comment by br1zey** [comment]
ok
