### ISSUE TITLE
suv für adac

### ISSUE THREAD

**Issue by PeetPunisher** [vabene1111/RL-4.0#169]
Da das abschleppen ja nun geht ;-)  gibt es leider den tow truck nicht mehr. aber es währe sehr schön wie bei der 3.0 den suv wieder hinzu zu fügen da dieser bei uns nur für meister und chefs war möchten wir das so bei der 4.0  beibehalten. es gibt in aber nicht zu kaufen. dafür könnte das atv entfernt werden mann kann es für nix gebrauchen

**Comment by vabene1111** [comment]
welchen suv ? am besten class name oder namen des fahrzeugs

**Comment by PeetPunisher** [comment]
das fahrzeug heist suv ist ein arma internes fahrzeug, ebenfalls sollich fragen weshalb der tow truck entfernt wurde und ob es die möglichkeit gibt evtl zb den intercepter einzufügen.mfg adac leitung. crunchy und buffer

**Comment by vabene1111** [comment]
tow truck war a3l was einfach nur mist ist und weg kommt .. 
normalen suv bekommt ihr kein problem

**Comment by PeetPunisher** [comment]
ok, es gab mal einen adac skin für den :  dezkit_b206_ems    IST DER mod heli den die zivs bei der 3.0 mom auch kaufen könne
