### ISSUE TITLE
Mehr Bank Automaten 

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/RL-4.0#29]

**Comment by Thomas-Ace** [comment]
Melbourne 2 neue ATM´s -> http://prntscr.com/8zqe0h

**Comment by Thomas-Ace** [comment]
Sydney 1 neuer ATM -> Später

**Comment by Thomas-Ace** [comment]
Willcania 1 neuer ATM -> Später

**Comment by Thomas-Ace** [comment]
Toowoomba 1 neuer ATM -> Später

**Comment by Thomas-Ace** [comment]
Perth 1 neuer ATM -> Später
