### ISSUE TITLE
Gefängnis klappt das einsperren nicht

### ISSUE THREAD

**Issue by pyrox25** [vabene1111/RL-4.0#53]
Man kann niemanden am Gefängnis (Staatsgefängnis) eingknasten. Folgende Benachrichtigung erscheint: Der Spieler muss in Handschellen mit Shift+R gelegt werden

**Comment by vabene1111** [comment]
http://images.akamai.steamusercontent.com/ugc/394423611542985135/CB19109CF30B051158484E0709FA18D5A2CEE1E4/
