### ISSUE TITLE
Spiel freezt ein

### ISSUE THREAD

**Issue by pyrox25** [vabene1111/RL-4.0#55]
Bei 90 % der Tester ist gegen Mitternacht, das komplette Spiel eingefreezt. Ohne Fehlermeldung
Bei mir 2 mal während dem Fliegen, als ich in den Jet´s drinne war.
Bei der Oespry keine Probleme gehabt.
Nach #reassign ist dieses Problem nicht mehr augetreten,
Eventuell zulange Laufzeit?

**Comment by vabene1111** [comment]
Schein beim autosave bei hoher geschwindigkeit zu sein
