### ISSUE TITLE
Autohaus

### ISSUE THREAD

**Issue by Devil82** [vabene1111/RL-4.0#58]
Beim einkauf von Fahrzeugen, bei der Auswahl überlappen sich die Auto´s und gehen dabei hoch.
http://grabilla.com/05b06-5d98349d-dabe-4a55-81c1-365c6188a06a.html# das Problem wird dann nur sein wenn 2-3 Spieler es machen packt die Datenbank es nicht!!!!

**Comment by vabene1111** [comment]
scheint nicht lokal zu sapwnen

**Comment by vabene1111** [comment]
explosion wird gesynct, daher muss speed change verhindert werden
