### ISSUE TITLE
Marktplatz verkleinern

### ISSUE THREAD

**Issue by pyrox25** [vabene1111/RL-4.0#72]
Der Marktplätze sollten verkleinert werden. Unbenutzte Stände entfernen, ggf. Parkplätze draus machen?

**Comment by Thomas-Ace** [comment]
Wird gemacht Packplätze für Cop, Med und ADAC daraus machen? evtl. paar Ziv raus?

**Comment by Thomas-Ace** [comment]
Map Gebäude müssten extra entfernt werden, verkleinnerung nicht möglich! Parkplätze erstmal nicht möglich

**Comment by br1zey** [comment]
Es sinde feste Gebäude daher hier nicht möglich
