### ISSUE TITLE
COP Hubschrauber HQ nördlich keine Minibilder beim Kauf

### ISSUE THREAD

**Issue by Trefferquote0** [vabene1111/RL-4.0#85]

**Comment by vabene1111** [comment]
was meinst du mit minibilder ?

**Comment by Trefferquote0** [comment]
Na wenn ich nen Hubschrauber kaufen will, kam so eine Art Minibild oder Vorschau...das kam bei dem Shop aber nicht. Möglicherweise auch kein Bug

**Comment by Trefferquote0** [comment]
Schließ mal bitte das Ticket. Ich kann das schlecht beschreiben.
