### ISSUE TITLE
COP HQ Victoria Shop hat nicht die selbe "Triggerentfernung" wie der integrierte Bankautomat

### ISSUE THREAD

**Issue by Trefferquote0** [vabene1111/RL-4.0#87]

**Comment by vabene1111** [comment]
?

**Comment by Trefferquote0** [comment]
Also wenn man mit dem Cursor (aus sagen wir 15m) zum Shop guckt, hat man schon ein Auswahlmenü, aber für den Bankautomat muss man näher rangehen an den Shop

**Comment by vabene1111** [comment]
das ist arma ...
