### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by Sylter** [vabene1111/RL-4.0#93]
wenn ich in einem Radius von unter 1000 Metern zur Eisenverarbeitung komme freezt das Game und man muss es neu starten, die Entfernung variiert aber erst ab unter 1000 Metern

**Comment by Greenywastaken** [comment]
Error: Vertex shader ID out of limits, eg. A2 Item "p_Helianthus"

**Comment by vabene1111** [comment]
in der Nähe von der Kupferschmiede bei Melbourne habe ich zweimal in Folge ein Freeze mit dem Merlin gehabt
ich war zwischen 200 und 400 m Höhe, 264 Km/h schnell, Fluggerät Merlin
anbei ein Bild mit der ungefähren Stelle
http://www.pic-upload.de/view-28807962/Freezepunkt2.png.html
